{{- if .Values.nacos.service.enable}}
kind: Service
apiVersion: v1
metadata:
  name: nacos
  labels:
    app: nacos
spec:
  ports:
    - name: http-server
      port: 8848
      targetPort: 8848
      nodePort: {{ .Values.nacos.service.nodePort }}
  selector:
    app: nacos
  type: NodePort
{{- end}}